config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get 'search' => 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  attachment :image

  validates :title, presence: true
	validates :body, presence: true

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def self.search(word)
    unless word == ""
      @article = Article.where("title LIKE?","%#{word}%")
    else
      @article = Article.all
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :content, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  attachment :profile_image

  validates :name, length: {maximum: 20, minimum: 1}, uniqueness: true

  has_many :comments, dependent: :destroy

  #既にいいねしているかどうか
# def already_liked?(article)
#   self.favorites.exists?(article_id: article.id)
# end

has_many :favorites, dependent: :destroy

has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
def follow(user_id)
  relationships.create(followed_id: user_id)
end
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
def following?(user)
  followings.include?(user)
end

def self.search_for(word)
   unless word == ""
       User.where("name LIKE?","%#{word}%")
    else
       User.all
    end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    articles_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
       redirect_to article_path(@article), notice: "You have created book successfully."
    else
       @articles = Article.all
       @user = current_user
       render 'new'
    end
  end

  def index
    @articles = Article.all.order(created_at: :desc)
    @articles = Article.page(params[:page]).reverse_order
  end

  def edit
    @article = Article.find(params[:id])
    if @article.user != current_user
      redirect_to articles_path
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :image, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @article = Article.find(params[:article_id])
      #投稿に紐づいたコメントを作成
      @comment = @article.comments.build(comment_params)
      @comment.user_id = current_user.id
      @comment.save
        render :comments
  end

  def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
        render :comments
  end

  private
  def comment_params
      params.require(:comment).permit(:content, :article_id, :user_id)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    favorite = @article.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = @article.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # ——————フォロー機能を作成・保存・削除する————————————
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
#————————フォロー・フォロワー一覧を表示する-————————————
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    word = params[:word]
    if @range == '1'
      @user = User.search_for(word)
    else
      @article = Article.search(word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash.now[:alert]
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_index.html.erb
<% articles.each do |article| %>
<div class='container'>
  <article class="comic">
    <div class="panel">

        <%= link_to user_path(article.user) do %>
          <%= attachment_image_tag(article.user, :profile_image, :fill, 50, 50, fallback: "imgshake2.png") %>
        <% end %>
        <%= article.user.name %>
      <% if article.image_id %>
        <canvas class="DstCanvas"></canvas>
      <% end %>

      <div id="article_<%= article.id %>">
        <div class="favorite"><%= render "favorites/favorite", article: article %></div>
        <div class="<%= article.image_id ? 'imgshake' : '' %>" hidden><%= attachment_image_tag article, :image, :fill, 510, 340, size: "510x340" %></div>
      </div>

      <p class="text bottom-right">
        <span style="background-color:#fcc800">
          <%= link_to article.title, article_path(article), class: "article_#{article.id}" %>
        </span>
      </p>

    </div>
  </article>
</div>
<% end %>
<div class="kaminari"><%= paginate @articles %></div>

app/views/articles/edit.html.erb
<div class='container'>
  <div class="card">
    <div class="card-body">
      <h1>編集</h1>
      <%= form_with model: @article, local:true do |f| %>
        <h4>画像</h4>
        <%= f.attachment_field :image %>
        <h4>タイトル</h4>
        <%= f.text_field :title, size: "2x1", class: "form-control" %>
        <h4>説明</h4>
        <%= f.text_area :body, size: "20x10", class: "form-control" %>
        <%= f.submit '編集' %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<%= render 'index', articles: @articles %>

app/views/articles/new.html.erb
<div class='container'>
  <div class="card">
    <div class="card-body">
      <div class="text-center">
        <h1>投稿フォーム</h1>
        <%= form_with model: @article, local:true do |f| %>
          <%= render 'layouts/errors', model: f.object %>
      </div>
          <h4>画像</h4>
          <!--<2%= f.file_field :image %>-->
          <%= f.attachment_field :image %>
          <h4>タイトル</h4>
          <%= f.text_field :title, size: "2x1", class: "form-control" %>
          <h4>一言感想</h4>
          <%= f.text_area :body, size: "20x10", class: "form-control" %>
          <%= f.submit '投稿' %>
        <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='container px-5 px-sm-0'>
      <article >
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <div class="panel">
            <canvas id="DstCanvas"></canvas>
            <div id="imgshake" hidden><%= attachment_image_tag @article, :image, :fill, 500, 500 %></div>

            <div class="kaigyo">
              <%= link_to user_path(@article.user) do %>
                <%= attachment_image_tag(@article.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "imgshake2.png") %>
                <%= @article.user.name %>
              <% end %>
              <p>タイトル：<%= @article.title %></p>
              <p>説明：<%= @article.body %></p>

              <p class="text bottom-right">投稿日時：<%= @article.created_at.strftime('%Y/%m/%d') %></p>
              <% if @article.user == current_user %>
                <%= link_to '編集', edit_article_path(@article) %>
                <%= link_to "削除", article_path(@article), method: :delete, data: { confirm: '本当に消しますか？' } %>
              <% end %>
            </div>

            <div id="article_<%= @article.id %>">
              <div class="favorite"><%= render "favorites/favorite", article: @article %></div>
            </div>
          </div>
        </div>
      </article>
    </div>

    <div class='container w-50'>
        <div class="card">
          <div class="card-body">
            <div class='container'>
                <div>
                  <% if user_signed_in? %>
                    <div class="comment-create">
                      <h3>コメントを投稿する</h3>
                      <%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>
                    </div>
                  <% end %>

                  <div id="comments_area">
                    <%= render partial: 'comments/comments', locals: { comments: @comments } %>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comments.html.erb
<%= comments.count %>件コメント
<div>
  <% comments.each do |comment| %>
  <% unless comment.id.nil? %>

  <div class="comment">
    <div class="icon">
      <%= attachment_image_tag comment.user, :profile_image, fallback: "imgshake2.png", class:"comment-image", size: "40x40" %>
    </div>
    <%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %>
    <% if comment.user == current_user %>
    　<%= link_to article_comment_path(comment.article_id, comment.id), method: :delete, remote: true do %>
      <i class="fas fa-trash" style="color: black;"></i>
    <% end %>
    <% end %>
  </div>

    <%= comment.content %>
　 <p><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
    <% end %>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [article, comment], url: article_comments_path(@article) ) do |form| %>
  <%= form.text_area :content, size: "7x5", class: "form-control"  %>
  <%= form.submit "送信" %>
<% end %>

app/views/comments/comments.js.erb
$("#comments_area").html("<%= j(render 'comments', { comments: @comment.article.comments }) %>")
$("textarea").val('')

app/views/favorites/_favorite.html.erb
<% if article.favorited_by?(current_user) %>
  <%= link_to article.favorites.count, article_favorites_path(article), method: :delete, remote: true, class: "fas fa-heart" %>
<% else %>
  <%= link_to article.favorites.count, article_favorites_path(article), method: :post, remote: true, class: "far fa-heart" %>
<% end %>

app/views/favorites/create.js.erb
$("#article_<%= @article.id %> .favorite").html("<%= j(render 'favorites/favorite', article: @article) %>");

app/views/favorites/destroy.js.erb
$("#article_<%= @article.id %> .favorite").html("<%= j(render 'favorites/favorite', article: @article) %>");

app/views/homes/top.html.erb
<div class="card">
  <p>ようこそIMG-しぇいくへ</p>
</div>
<div class="mt-3"></div>
<div class="card">
  <p>IMG-しぇいくとは、</p>
</div>
<div class="mt-5"></div>
<div class="card">
  <p>元画↓</p>
  <%= image_tag 'byodoin.jpg'%>
  <div class="mt-5"></div>
  <p>投稿後↓</p>
  <canvas id="DstCanvas"></canvas>
  <div id="imgshake" hidden><%= image_tag 'byodoin.jpg' %></div>
</div>
<div class="mt-5"></div>
<div class="card">
  <p>このように画像がブレブレになる、画像投稿サイトです</p>
</div>
<div class="mt-3"></div>
<div class="card">
  <p>私のように、手振れ写真が多く占めている人。</br>
  綺麗に写真を撮れる人だけれど、たまにはネタに走りたい人</br>
  写真によって身バレを怖がるがSNSをやりたい人</br>
  描いた絵や、綺麗にできたものにもうひと手間主観を加えたい人</br>
  </p>
</div>
<div class="mt-4"></div>
<div class="card">
  <h3>ふと撮った写真をブレブレにして、仲間と楽しみませんか♪</h3>
</div>
<div class="mt-4"></div>
<li class="btn-group mr-5" role="group" aria-label="First group" style="background-color: rgb(250, 253, 255);">
  <%= link_to "Sign-up", new_user_registration_path %>
</li>
<li class="btn-group mr-5" role="group" aria-label="Second group" style="background-color: rgb(250, 253, 255);">
  <%= link_to "Log-in", new_user_session_path %>
</li>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "Follow", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class="card">
  <h2>Follower Users</h2>
  <table class='table'>
    <% if @users.exists? %>

    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "imgshake2.png") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
      <% end %>
    </tbody>
    <% else %>
      <p>ユーザーはいません</p>
    <% end %>
  </table>
</div>

app/views/relationships/followings.html.erb
<div class="card">
  <h2>Follow Users</h2>
  <table class='table'>
    <% if @users.exists? %>

    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "imgshake2.png") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
      <% end %>
    </tbody>
    <% else %>
      <p>ユーザーはいません</p>
    <% end %>
  </table>
</div>

app/views/searches/search.html.erb
<div class="card">
  <table class="table table-hover table-inverse">
     <% if @range == '2' %>
     <h2>Article search for "<%= (params[:word]) %>"</h2>
     <thead>
      <tr>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
       <% @article.each do |article| %>
        <tr>
         <td>
           <%= link_to article.title.truncate(30), article, class: "article_#{article.id}" %>
         </td>
         <td><%= article.body.truncate(50) %></td>
        </tr>
       <% end %>
     </tbody>

    <% else %>
    <h2>Users search for "<%= (params[:word]) %>"</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "imgshake2.png") %></td>
          <td><%= user.name%></td>
          <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
    <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class="card">
    <div class="card-body">
      <h2>プロフィール編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <h4>ProfileImage</h4>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <h4>Name</h4>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", size: "2x1", class: "form-control"%>
        <h4>Introduction</h4>
        <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"紹介文", size: "20x10", class: "form-control"%>

        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="my">
  <div class="name">neme:<%= @user.name %></div>
  <div class="introduction">紹介文:
    <div><%= @user.introduction %></div>
  </div>
  <div class="profile_image">
    <%= attachment_image_tag @user, :profile_image, size:"50x50", format: 'jpeg', fallback: "imgshake2.png" %>
  </div>
  <div class="boxContainer">
    <div class="box">投稿数:<%= @user.articles.count %></div>
    <div class="box">コメ数:<%= @user.comments.count %></div>
    <div class="box">
      follows:<%= link_to "#{@user.followings.count}", user_followings_path(@user.id) %>
    </div>
    <div class="box">
      followers:<%= link_to "#{@user.followers.count}", user_followers_path(@user.id) %>
    </div>
  </div>

  <div class="prof">
    <% if @user.id == current_user.id %>
      <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
    <% end %>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>

<% @articles.each do |article| %>
  <div class='container'>
    <article class="comic">
      <div class="panel">

      <% if article.image_id %>
      <canvas class="DstCanvas"></canvas>
       <% end %>

      <%= link_to article_path(article.id) do %>
        <div class="<%= article.image_id ? 'imgshake' : '' %>" hidden><%= attachment_image_tag article, :image, :fill, 510, 340, size: "510x340" %></div>
      <% end %>
      <%= link_to article_path(article.id) do %>
        <p>タイトル：<%= article.title %></p>
      <% end %>
        <p>説明：<%= article.body %></p>
       </div>
    </article>
  </div>
<% end %>