config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get 'search' => 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  attachment :image

  validates :title, presence: true
	validates :body, presence: true

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def self.search(word)
    unless word == ""
      @article = Article.where("title LIKE?","%#{word}%")
    else
      @article = Article.all
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :content, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  attachment :profile_image

  validates :name, length: {maximum: 20, minimum: 1}, uniqueness: true

  has_many :comments, dependent: :destroy

  #既にいいねしているかどうか
# def already_liked?(article)
#   self.favorites.exists?(article_id: article.id)
# end

has_many :favorites, dependent: :destroy

has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
def follow(user_id)
  relationships.create(followed_id: user_id)
end
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
def following?(user)
  followings.include?(user)
end

def self.search_for(word)
   unless word == ""
       User.where("name LIKE?","%#{word}%")
    else
       User.all
    end
end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
       redirect_to article_path(@article), notice: "You have created book successfully."
    else
       @articles = Article.all
       @user = current_user
       render 'new'
    end
  end

  def index
    @articles = Article.all.order(created_at: :desc)
    @articles = Article.page(params[:page]).reverse_order
  end

  def edit
    @article = Article.find(params[:id])
    if @article.user != current_user
      redirect_to articles_path
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :image, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @article = Article.find(params[:article_id])
      #投稿に紐づいたコメントを作成
      @comment = @article.comments.build(comment_params)
      @comment.user_id = current_user.id
      @comment.save
        render :comments
  end

  def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
        render :comments
  end

  private
  def comment_params
      params.require(:comment).permit(:content, :article_id, :user_id)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    favorite = @article.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = @article.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    word = params[:word]
    if @range == '1'
      @user = User.search_for(word)
    else
      @article = Article.search(word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash.now[:alert]
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgShake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://kit.fontawesome.com/e52adb189d.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/" style="background-color: rgba(250, 253, 255, .8);"><span><%= image_tag 'imgshake.png', :size => '100x100'%></span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" style="background-color: rgba(250, 253, 255, .8);"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <div class="header-btn">
                <div class="text-center">

                  <% if user_signed_in? %>
                  <%= form_tag(search_path, method: :get) do %>
                    <%= select_tag 'range' ,options_for_select([['User', '1'], ['Title', '2']]) %>
                    <%= text_field_tag (:word) %>
                    <%= submit_tag "検索" %>
                  <% end %>

                  <div class="text-center">
                    <li class="btn-group mr-5" role="group" aria-label="First group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to 'Articles', articles_path %>
                    </li>
                    <li class="btn-group mr-5" role="group" aria-label="Second group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to 'New', new_article_path %>
                    </li>
                    <li class="btn-group mr-5" role="group" aria-label="Third group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to 'My-Page', user_path(current_user.id) %>
                    </li>
                    <li class="btn-group mr-5" role="group" aria-label="Fourth group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to "Log-out", destroy_user_session_path, method: :delete %>
                    </li>

                  <% else %>
                    <li class="btn-group mr-5" role="group" aria-label="First group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to "Sign-up", new_user_registration_path %>
                    </li>
                    <li class="btn-group mr-5" role="group" aria-label="Second group" style="background-color: rgb(250, 253, 255);">
                      <%= link_to "Log-in", new_user_session_path %>
                    </li>
                  <% end %>
                  </div>
                </div>
              </div>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="cont">
    <%= yield %>
    </div>

    <footer>
  	  <p>IMG-Shake 2021-7</p>
    </footer>
  </body>
</html>